### ISSUE TITLE
Please use github tag o releases

### ISSUE THREAD

**Issue by ftoledo** [M-griffin/EtherTerm#22]
Hi! i'm working on packaging EtherTerm for Debian.

I'm very grateful if you can tag o release the code of github. In this way is easy to use tools like watch files and uscan to download specific versions and notify for new releases.
You can use, for example "git tag v2.8" to create a new tag to the code tree.

I will fill a ITP (intent to package) report in the Debian bugtracker a will work on it. 

Thank you!

**Comment by M-griffin** [comment]
Hi Fernando, I'll take a look at that when I get some time later tonight.  Thanks for your interest!  Just a note though, the code is still in early development, and a large rewrite is going on in the 3.0 Demo branch.  I don't know if this program is ready for a full package since is still in early preview stages.

**Comment by M-griffin** [comment]
2.8 is now tagged.  :+1:

**Comment by ftoledo** [comment]
Very good! im intereseted on package it, im also work in SyncTerm packaging. I can wait to better releases, in the meantime i can advance on building the package.
